In [1]:
from transformers import pipeline

In [2]:
# bert-base-uncased is bert model provided by huggingface
unmasker = pipeline('fill-mask',model='bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [3]:
unmasker("Hello I'm a [MASK] university student from South Korea.")

[{'sequence': "hello i'm a korean university student from south korea.",
  'score': 0.19418807327747345,
  'token': 4759,
  'token_str': 'korean'},
 {'sequence': "hello i'm a young university student from south korea.",
  'score': 0.05836235359311104,
  'token': 2402,
  'token_str': 'young'},
 {'sequence': "hello i'm a fellow university student from south korea.",
  'score': 0.03686646744608879,
  'token': 3507,
  'token_str': 'fellow'},
 {'sequence': "hello i'm a chinese university student from south korea.",
  'score': 0.03416597098112106,
  'token': 2822,
  'token_str': 'chinese'},
 {'sequence': "hello i'm a visiting university student from south korea.",
  'score': 0.03217637538909912,
  'token': 5873,
  'token_str': 'visiting'}]

In [13]:
from transformers import BertTokenizer, TFBertModel

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model= TFBertModel.from_pretrained('bert-base-uncased')
# tokenizer -> dataloader(preprocessing data) -> model
text1 ="Is this a valid sentence?"
text2 = "I am student running to Yonsei University building."
text3 = " My favorite Programming Language is C++."
text = [text1,text2,text3]
encoded_inputs = tokenizer(text, return_tensors='tf',return_attention_mask=True,padding=True,truncation=True)
print(encoded_inputs)

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


{'input_ids': <tf.Tensor: shape=(3, 13), dtype=int32, numpy=
array([[  101,  2003,  2023,  1037,  9398,  6251,  1029,   102,     0,
            0,     0,     0,     0],
       [  101,  1045,  2572,  3076,  2770,  2000, 10930, 12325,  2072,
         2118,  2311,  1012,   102],
       [  101,  2026,  5440,  4730,  2653,  2003,  1039,  1009,  1009,
         1012,   102,     0,     0]])>, 'token_type_ids': <tf.Tensor: shape=(3, 13), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(3, 13), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])>}


In [14]:
encoded_inputs['input_ids']

<tf.Tensor: shape=(3, 13), dtype=int32, numpy=
array([[  101,  2003,  2023,  1037,  9398,  6251,  1029,   102,     0,
            0,     0,     0,     0],
       [  101,  1045,  2572,  3076,  2770,  2000, 10930, 12325,  2072,
         2118,  2311,  1012,   102],
       [  101,  2026,  5440,  4730,  2653,  2003,  1039,  1009,  1009,
         1012,   102,     0,     0]])>

In [15]:
print(tokenizer.decode(encoded_inputs['input_ids'][0]))
print(tokenizer.decode(encoded_inputs['input_ids'][1]))
print(tokenizer.decode(encoded_inputs['input_ids'][2]))

[CLS] is this a valid sentence? [SEP] [PAD] [PAD] [PAD] [PAD] [PAD]
[CLS] i am student running to yonsei university building. [SEP]
[CLS] my favorite programming language is c + +. [SEP] [PAD] [PAD]


In [16]:
encoded_input2 = tokenizer("What is your name?","My name is Seungone.",return_tensors='tf')
print(encoded_input2)

{'input_ids': <tf.Tensor: shape=(1, 15), dtype=int32, numpy=
array([[ 101, 2054, 2003, 2115, 2171, 1029,  102, 2026, 2171, 2003, 7367,
        5575, 5643, 1012,  102]])>, 'token_type_ids': <tf.Tensor: shape=(1, 15), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]])>, 'attention_mask': <tf.Tensor: shape=(1, 15), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])>}


In [18]:
print(tokenizer.decode(encoded_input2['input_ids'][0]))

[CLS] what is your name? [SEP] my name is seungone. [SEP]


In [19]:
output = model(encoded_inputs)
print(output)

TFBaseModelOutputWithPooling(last_hidden_state=<tf.Tensor: shape=(3, 13, 768), dtype=float32, numpy=
array([[[ 0.1584683 ,  0.05394202, -0.02173148, ..., -0.1263333 ,
          0.06896812,  0.46639672],
        [ 0.12491301, -0.1220137 , -0.03282016, ...,  0.3831069 ,
          1.0131848 ,  0.6159238 ],
        [-0.20566858, -0.6244838 ,  0.16080046, ..., -0.00229507,
         -0.05117407,  0.5581342 ],
        ...,
        [ 0.22871093,  0.44744945,  0.3578546 , ...,  0.46337926,
          0.10052502, -0.2444902 ],
        [ 0.18982568, -0.05153685, -0.08534762, ...,  0.3760352 ,
          0.197602  , -0.27288702],
        [ 0.1412916 , -0.01042851, -0.01311123, ...,  0.36208832,
          0.18744272, -0.21668495]],

       [[-0.22801131,  0.15609686,  0.22225544, ..., -0.577901  ,
          0.35622063,  0.18715926],
        [-0.16532849, -0.3931642 ,  0.09108079, ..., -0.5639909 ,
          0.07929863, -0.29892743],
        [-0.3986258 , -0.07625765,  0.6550277 , ..., -0.6394473 ,
  

In [34]:
from transformers import BertTokenizer, TFBertForMaskedLM
import tensorflow as tf

tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
model = TFBertForMaskedLM.from_pretrained('bert-base-cased')

inputs = tokenizer("The capital of France is [MASK].", return_tensors="tf")
inputs["labels"] = tokenizer("The capital of France is Paris.", return_tensors="tf")["input_ids"]

outputs = model(inputs)
loss = outputs.loss
logits = outputs.logits

print(outputs)
print()
print(loss)
print()
print(logits)

All model checkpoint layers were used when initializing TFBertForMaskedLM.

All the layers of TFBertForMaskedLM were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


TFMaskedLMOutput(loss=<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.2178121e+01, 5.3454580e+00, 9.5798366e-04, 6.0269046e-03,
       3.3788753e-03, 5.6930067e-04, 8.1031382e-01, 4.1392818e-04,
       2.3580479e+01], dtype=float32)>, logits=<tf.Tensor: shape=(1, 9, 28996), dtype=float32, numpy=
array([[[ -7.1545234,  -6.9931316,  -7.182646 , ...,  -5.9123926,
          -5.6732936,  -5.9854193],
        [ -8.018968 ,  -8.13193  ,  -8.050915 , ...,  -6.5679274,
          -6.4058185,  -6.8997593],
        [ -4.977202 ,  -6.1780906,  -6.066909 , ...,  -5.636203 ,
          -4.6602654,  -5.124104 ],
        ...,
        [ -3.4420216,  -3.2557287,  -3.5732915, ...,  -2.460596 ,
          -2.6494863,  -3.195194 ],
        [-10.588984 , -10.462034 , -11.718096 , ...,  -7.4646177,
          -9.954243 ,  -8.39268  ],
        [-14.889968 , -14.887321 , -14.45686  , ..., -11.658825 ,
         -13.0151005, -11.607314 ]]], dtype=float32)>, hidden_states=None, attentions=None)

tf.Tensor(
[1.

In [44]:
from transformers import FillMaskPipeline

pipeline = FillMaskPipeline(model,tokenizer)

result = pipeline("The capital of France is [MASK].")
print(result)

[{'sequence': 'The capital of France is Paris.', 'score': 0.44471848011016846, 'token': 2123, 'token_str': 'P a r i s'}, {'sequence': 'The capital of France is Lyon.', 'score': 0.09396772086620331, 'token': 10067, 'token_str': 'L y o n'}, {'sequence': 'The capital of France is Toulouse.', 'score': 0.0823521688580513, 'token': 18367, 'token_str': 'T o u l o u s e'}, {'sequence': 'The capital of France is Lille.', 'score': 0.07515732944011688, 'token': 25411, 'token_str': 'L i l l e'}, {'sequence': 'The capital of France is Marseille.', 'score': 0.05692743510007858, 'token': 17851, 'token_str': 'M a r s e i l l e'}]
